export const carOptions = {
  Toyota: [
    "Corolla",
    "Camry",
    "Yaris",
    "RAV4",
    "Highlander",
    "Land Cruiser",
    "Prius",
    "Hilux",
  ],
  Honda: [
    "Civic",
    "Accord",
    "CR-V",
    "Pilot",
    "Fit",
    "HR-V",
    "Odyssey",
    "Insight",
  ],
  Ford: [
    "Fiesta",
    "Focus",
    "Fusion",
    "Escape",
    "Explorer",
    "F-150",
    "Mustang",
    "Edge",
  ],
  BMW: ["3 Series", "5 Series", "7 Series", "X1", "X3", "X5", "i3", "M3"],
  Mercedes: [
    "A-Class",
    "C-Class",
    "E-Class",
    "S-Class",
    "GLA",
    "GLC",
    "GLE",
    "G-Class",
  ],
  Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "TT"],
  Volkswagen: [
    "Golf",
    "Polo",
    "Passat",
    "Jetta",
    "Tiguan",
    "Touareg",
    "Arteon",
    "Beetle",
  ],
  Hyundai: [
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Kona",
    "i30",
    "Accent",
    "Palisade",
  ],
  Kia: [
    "Rio",
    "Cerato",
    "Sportage",
    "Sorento",
    "Soul",
    "Seltos",
    "Stinger",
    "Picanto",
  ],
  Nissan: [
    "Micra",
    "Sentra",
    "Altima",
    "Maxima",
    "Rogue",
    "Murano",
    "Pathfinder",
    "370Z",
  ],
  Chevrolet: [
    "Spark",
    "Cruze",
    "Malibu",
    "Equinox",
    "Traverse",
    "Tahoe",
    "Camaro",
    "Silverado",
  ],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y", "Roadster", "Cybertruck"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "CX-9", "MX-5"],
  Subaru: [
    "Impreza",
    "Legacy",
    "Forester",
    "Outback",
    "Crosstrek",
    "BRZ",
    "WRX",
  ],
  Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
  Jeep: [
    "Renegade",
    "Compass",
    "Cherokee",
    "Grand Cherokee",
    "Wrangler",
    "Gladiator",
  ],
  Peugeot: ["208", "308", "508", "2008", "3008", "5008"],
  Renault: ["Clio", "Megane", "Captur", "Kadjar", "Talisman", "ZOE"],
  Skoda: ["Fabia", "Octavia", "Superb", "Karoq", "Kodiaq", "Scala"],
  LandRover: [
    "Defender",
    "Discovery",
    "Range Rover",
    "Range Rover Evoque",
    "Velar",
  ],
};

export const gearboxOptions = ["Manual", "Automatic"];
export const fuelTypeOptions = ["Petrol", "Diesel", "Electric", "Hybrid", "Gas"];
export const engineTypeOptions = [
  "Inline-4",
  "Inline-6",
  "V6",
  "V8",
  "V10",
  "V12",
  "Boxer (Flat-4 / Flat-6)",
  "Rotary (Wankel)",
  "Electric Motor",
  "Hybrid Engine",
  "Turbocharged",
  "Supercharged",
];

export const colorOptions = [
  "Black",
  "White",
  "Silver",
  "Red",
  "Blue",
  "Gray",
  "Green",
  "Yellow",
  "Orange",
  "Brown",
  "Beige",
];

export const sortByOptions = [
    { value: "Brand-asc", label: "Brand (A-Z)" },
    { value: "Brand-desc", label: "Brand (Z-A)" },
    { value: "Model-asc", label: "Model (A-Z)" },
    { value: "Model-desc", label: "Model (Z-A)" },
    { value: "Price-asc", label: "Price (Low to High)" },
    { value: "Price-desc", label: "Price (High to Low)" },
    { value: "Created-asc", label: "Created (Oldest First)" },
    { value: "Created-desc", label: "Created (Newest First)" },
  ];
  